name: Build CLI on MacOS

on: push

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Upload soup
        uses: actions/upload-artifact@v3
        with:
          name: "MacOS (X86)"
          path: CLI/soup
