name: Build CLI

on: push

jobs:
  ubuntu-22-04:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

  ubuntu-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

  debian-10:
    runs-on: [debian-10]
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Debian 10 and above"
          path: CLI/soup

  macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: ./CLI/soup test

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "MacOS (X86)"
          path: CLI/soup

  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Soup
        run: php build_lib.php

      - name: Build CLI
        run: php build_cli.php

      - name: Run ./soup test
        run: CLI/soup.exe test

      - name: Upload soup
        uses: actions/upload-artifact@v4
        with:
          name: "Windows"
          path: CLI/soup.exe
