name: Build WASM library

on: push

jobs:
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v13

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.EMSDK }}/upstream/emscripten/cache
          key: wasm

      - uses: actions/checkout@v4

      - name: Build
        run: php wasm.php

      - name: Ensure files exist
        uses: andstor/file-existence-action@v2
        with:
          files: "bindings/libsoup.js, bindings/libsoup.wasm"
          fail: true

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "WASM"
          path: |
            bindings/libsoup.js
            bindings/libsoup.wasm
