name: Build WASM library

on:
  push:
    branches: [ "senpai" ]

jobs:
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v12

      - uses: actions/checkout@v3

      - name: Build
        run: php wasm.php

      - name: Ensure files exist
        uses: andstor/file-existence-action@v2
        with:
          files: "bindings/libsoup.js, bindings/libsoup.wasm"
          fail: true

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "WASM"
          path: |
            bindings/libsoup.js
            bindings/libsoup.wasm
